[package]
name = "imget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
notify = "6.1.1"
notify-debouncer-mini = "0.4.1"
serde = { version = "1.0", features = ["derive"] }